version: '3.8'
services:
  php:
    container_name: php-container
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/srv/www
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}

  apache:
    container_name: apache-container
    image: httpd:latest
    ports:
      - 8088:80
    volumes:
      - .:/srv/www
      - ./docker/vhost.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php

  my-database-service:
    container_name: db-container
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "13306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: my-database-service
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - my-database-service

volumes:
  dbdata:
    driver: "local"