name: webpage-template-deployment

on:
    push:
        branches: [master]

env:
    # It tells the runner: execute JavaScript-based actions using Node.js 24.
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
    install-composer-dependencies:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  extensions: mbstring, intl, pdo, pdo_mysql, dom, xml, xmlwriter, gd, zip, soap, calendar

# store and reuse downloaded dependencies between workflow runs 
            - name: Cache Composer dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.composer/cache
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

            - name: Install Composer dependencies
              run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

# Composer installs packages into /vendor. To make things faster, we install it only in the first job
# and later jobs will simply reuse the vendor dir. So we upload the vendor back to Github Actions storage
            - name: Upload vendor artifact
              uses: actions/upload-artifact@v4
              with:
                  name: vendor
                  path: vendor


    cs-fixer:
        runs-on: ubuntu-latest
        needs: install-composer-dependencies

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download vendor artifact
              uses: actions/download-artifact@v4
              with:
                  name: vendor
                  path: vendor

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  extensions: mbstring, intl, pdo, pdo_mysql, dom, xml, xmlwriter, gd, zip, soap, calendar


            - name: Ensure php-cs-fixer is executable
              run: chmod +x vendor/bin/php-cs-fixer

            - name: Run PHP CS Fixer
              run: vendor/bin/php-cs-fixer fix --dry-run --diff --config=.php-cs-fixer.php


    phpstan:
        runs-on: ubuntu-latest
        needs: install-composer-dependencies

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download vendor artifact
              uses: actions/download-artifact@v4
              with:
                  name: vendor
                  path: vendor

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  extensions: mbstring, intl, pdo, pdo_mysql, dom, xml, xmlwriter, gd, zip, soap, calendar

            - name: Make PHPStan executable
              run: chmod +x vendor/bin/phpstan

            - name: Run PHPStan
              run: vendor/bin/phpstan analyse --memory-limit=512M --no-progress --error-format=github

    phpunit:
        runs-on: ubuntu-latest
        needs: install-composer-dependencies

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download vendor artifact
              uses: actions/download-artifact@v4
              with:
                  name: vendor
                  path: vendor

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  extensions: mbstring, intl, pdo, pdo_mysql, dom, xml, xmlwriter, gd, zip, soap, calendar

            - name: Copy .env
              run: cp .env.example .env

            - name: Make PHPUnit executable
              run: chmod +x vendor/bin/phpunit

            - name: Ensure storage logs directory exists
              run: mkdir -p storage/logs

            - name: Run PHPUnit
              run: vendor/bin/phpunit


    deploy:
        runs-on: ubuntu-latest
        needs: [cs-fixer, phpstan, phpunit]
        steps:
            - name: Deploy via SSH
# Below is a prebuilt GitHub Action to connect to a remote server via SSH.
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.ORACLE_HOST }}
                  username: ${{ secrets.ORACLE_USER }}
                  key: ${{ secrets.ORACLE_CHALLENGES_SSH_PRIVATE_KEY }}
# Everything below runs on Oracle server.
# set -e = If any command fails → stop execution immediately (fail fast behavior).
# cd /var/www/webpage-template = Change directory to the project folder on the remote server.
# git pull origin master = Fetch and merge the latest changes from the master branch.
# docker compose down = Stop and remove existing Docker containers, networks
# docker compose up -d --build = Rebuild images if needed and start containers in detached mode.
# docker compose exec -T php git config --global --add safe.directory /srv/www || true = Run Git config inside php container to mark directory as safe; ignore errors if it fails.
# docker compose exec -T php sh -lc 'XDEBUG_MODE=off composer install --no-interaction --prefer-dist --optimize-autoloader' = Run Composer install inside php container with optimizations and no prompts; disable Xdebug for speed.
# find cache -type d -exec chmod 775 {} + || true = Set directory permissions (rwxrwxr-x) for cache folders; ignore errors.
# find cache -type f -exec chmod 664 {} + || true = Set file permissions (rw-rw-r--) for cache files; ignore errors.
                  script: |
                      set -e
                      cd /var/www/webpage-template
                      echo "Pull latest code"
                      git pull origin master
                      echo "Rebuild containers"
                      docker compose down
                      docker compose up -d --build
                      echo "Configure git safe directory in php container"
                      docker compose exec -T php git config --global --add safe.directory /srv/www || true
                      echo "Install dependencies"
                      docker compose exec -T php sh -lc 'XDEBUG_MODE=off composer install --no-interaction --prefer-dist --optimize-autoloader'
                      echo "Fix permissions and ownership"
                      docker compose exec -T php chown -R www-data:www-data cache storage
                      docker compose exec -T php chmod -R 755 cache
                      docker compose exec -T php chmod -R 755 storage
       